const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
let token={value:null,expires:0};
async function shopifyToken(env){
  if(token.value&&Date.now()<token.expires)return token.value;
  if(!env.SHOPIFY_SHOP||!env.SHOPIFY_CLIENT_ID||!env.SHOPIFY_CLIENT_SECRET)throw new Error("Shopify is not configured");
  const r=await fetch(`https://${env.SHOPIFY_SHOP}.myshopify.com/admin/oauth/access_token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"client_credentials",client_id:env.SHOPIFY_CLIENT_ID,client_secret:env.SHOPIFY_CLIENT_SECRET})});
  const d=await r.json().catch(()=>({}));
  if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||"Shopify authentication failed");
  token={value:d.access_token,expires:Date.now()+Math.max(60,(Number(d.expires_in)||86399)-300)*1000};return token.value;
}
async function gql(env,query,variables={}){
  const t=await shopifyToken(env),r=await fetch(`https://${env.SHOPIFY_SHOP}.myshopify.com/admin/api/2026-07/graphql.json`,{method:"POST",headers:{"content-type":"application/json","X-Shopify-Access-Token":t},body:JSON.stringify({query,variables})});
  const d=await r.json().catch(()=>({}));if(!r.ok||d.errors?.length)throw new Error(d.errors?.[0]?.message||"Shopify API error");return d.data;
}
const catalog=`query{products(first:100,sortKey:CREATED_AT,reverse:true){nodes{id title handle productType tags images(first:3){nodes{url altText}} variants(first:100){nodes{id title sku price availableForSale selectedOptions{name value} image{url}}}}}}`;
const verify=`query($ids:[ID!]!){nodes(ids:$ids){... on ProductVariant{id title sku price availableForSale product{id title productType tags images(first:1){nodes{url altText}}}}}}`;
async function products(env){const d=await gql(env,catalog);return json({products:(d.products?.nodes||[]).map(p=>({id:p.id,title:p.title,handle:p.handle,productType:p.productType,tags:p.tags,images:p.images.nodes,variants:p.variants.nodes}))});}
function cfBase(env){return env.CASHFREE_ENV==="production"?"https://api.cashfree.com/pg":"https://sandbox.cashfree.com/pg"}
async function cashfree(env,o,origin){if(!env.CASHFREE_CLIENT_ID||!env.CASHFREE_CLIENT_SECRET)throw new Error("Cashfree is not configured");const r=await fetch(`${cfBase(env)}/orders`,{method:"POST",headers:{"content-type":"application/json","x-client-id":env.CASHFREE_CLIENT_ID,"x-client-secret":env.CASHFREE_CLIENT_SECRET,"x-api-version":env.CASHFREE_API_VERSION||"2025-01-01"},body:JSON.stringify({order_id:o.id,order_amount:o.amount,order_currency:"INR",customer_details:{customer_id:o.id,customer_name:o.customer.name,customer_email:o.customer.email,customer_phone:o.customer.phone},order_meta:{return_url:`${origin}/?payment=return&order_id=${encodeURIComponent(o.id)}`,notify_url:`${origin}/api/cashfree-webhook`}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Cashfree order creation failed");return d}
async function createPayment(req,env,origin){const b=await req.json().catch(()=>({})),c=b.customer||{},items=Array.isArray(b.items)?b.items:[];if(!c.name||!c.email||!c.phone||!items.length)return json({error:"Name, email, phone and items are required"},400);const clean=items.map(x=>({variantId:String(x.variantId||""),quantity:Math.max(1,Math.min(20,Number(x.quantity)||1))})).filter(x=>x.variantId);const d=await gql(env,verify,{ids:clean.map(x=>x.variantId)}),map=new Map((d.nodes||[]).filter(Boolean).map(x=>[x.id,x]));let amount=0;const safe=[];for(const x of clean){const v=map.get(x.variantId);if(!v)throw new Error("Selected Shopify variant was not found");if(v.availableForSale===false)throw new Error(`${v.product?.title||"Product"} is unavailable`);const p=Number(v.price);if(!Number.isFinite(p))throw new Error("Invalid Shopify price");amount+=p*x.quantity;safe.push({variantId:v.id,sku:v.sku||null,name:v.product?.title||v.title,variantTitle:v.title,quantity:x.quantity,unitPrice:p});}const id=`404_${Date.now()}_${crypto.randomUUID().slice(0,8)}`,now=new Date().toISOString(),cf=await cashfree(env,{id,customer:c,amount,items:safe},origin);if(env.DB)await env.DB.prepare(`INSERT INTO orders (id,cashfree_order_id,customer_name,customer_email,customer_phone,amount,currency,items_json,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(id,cf.order_id||null,c.name,c.email,c.phone,Math.round(amount*100),"INR",JSON.stringify(safe),"created",now,now).run();return json({payment_session_id:cf.payment_session_id,mode:env.CASHFREE_ENV==="production"?"production":"sandbox",order_id:id});}
async function webhook(req,env){const body=await req.text();let d={};try{d=JSON.parse(body)}catch{}if(env.DB&&d.order_id)await env.DB.prepare(`UPDATE orders SET status=?,updated_at=? WHERE id=? OR cashfree_order_id=?`).bind(d.order_status||d.payment_status||"webhook_received",new Date().toISOString(),d.order_id,d.order_id).run();return json({ok:true});}
export default{async fetch(req,env){const u=new URL(req.url);try{if(u.pathname==="/api/products"&&req.method==="GET")return products(env);if(u.pathname==="/api/create-payment"&&req.method==="POST")return createPayment(req,env,u.origin);if(u.pathname==="/api/cashfree-webhook"&&req.method==="POST")return webhook(req,env);return env.ASSETS.fetch(req);}catch(e){console.error(e);return json({error:e.message||"Server error"},500);}}};
